### ISSUE TITLE
error : not suitable for micropython in esp8266

### ISSUE THREAD

**Issue by viji2ks** [yschaeff/ICantBelieveItsNotDNS#1]
error : >>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
ImportError: no module named 'trusted_networks'

**Comment by yschaeff** [comment]
trusted_networks.py:

NETWORKS = {
    "essid":"password",
    "essid":"password",
    "essid":"password"
}


viji2ks ***@***.***> schreef op 4 april 2023 04:40:36 CEST:
>error : >>> %Run -c $EDITOR_CONTENT
>Traceback (most recent call last):
>  File "<stdin>", line 4, in <module>
>ImportError: no module named 'trusted_networks'
>
>
>
